name: Build and package on release

on:
  release:
    types: [created]

jobs:
  build-package:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        avx2: [true]
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Linux build deps
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake zip libvulkan-dev

      - name: Install Windows build deps
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          choco install -y cmake

      - name: Windows cache VulkanSDK
        if: runner.os == 'Windows'
        id: cache-vulkansdk
        uses: actions/cache@v4
        with:
          path: VulkanSDK
          key: VulkanSDK-1.3.268.0-Installer

      - name: Windows install VulkanSDK
        if: runner.os == 'Windows' && steps.cache-vulkansdk.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.4.328.1/windows/vulkansdk-windows-X64-1.4.328.1.exe?Human=true" -OutFile vulkansdk-windows-X64-1.4.328.1.exe
          7z x -aoa ./vulkansdk-windows-X64-1.4.328.1.exe -oVulkanSDK

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Rust (release)
        env:
          RUSTFLAGS: ${{ matrix.avx2 && '-C target-feature=+avx2' || '' }}
        run: cargo build --release --locked

      - name: Linux build rife-ncnn-vulkan
        if: runner.os == 'Linux'
        shell: bash
        run: |
          set -e
          pushd rife-ncnn-vulkan
          git submodule update --init --recursive
          mkdir -p build
          cd build
          cmake ../src -DCMAKE_BUILD_TYPE=Release || cmake ..
          cmake --build . -- -j 4
          popd

      - name: Windows build rife-ncnn-vulkan
        if: runner.os == 'Windows'
        shell: pwsh
        env:
          VULKAN_SDK: ${{ runner.workspace }}/VulkanSDK
        run: |
          $ErrorActionPreference = "Stop"
          pushd rife-ncnn-vulkan
          git submodule update --init --recursive
          mkdir build -Force
          cd build
          $env:VULKAN_SDK = "$(pwd)/VulkanSDK"
          cmake ../src -DCMAKE_BUILD_TYPE=Release
          cmake --build . -- -j 4
          popd

      - name: Prepare package layout and copy files (Linux)
        if: runner.os == 'Linux'
        run: |
          set -e
          PKG=package-${{ matrix.os }}-${{ matrix.avx2 }}
          rm -rf "$PKG"
          # Copy top-level release executables only. Avoid deps, rlib, dSYM, *.d files
          for f in target/release/*; do
            if [ -f "$f" ] && [ -x "$f" ]; then
              base=$(basename "$f")
              case "$base" in
                *.d|*.rlib|*.rmeta|*.dSYM|*.dwo) continue ;;
                deps) continue ;;
                *) cp -v "$f" "$PKG/" ;;
              esac
            fi
          done
          # Include project files
          cp -v LICENSE README.md log_viewer.py "$PKG/" || true
          mkdir -p "$PKG/DuplicateDetect/models"
          cp -v DuplicateDetect/models/* "$PKG/DuplicateDetect/models/" || true
          mkdir -p "$PKG/MotionPredictor/models"
          cp -v MotionPredictor/models/* "$PKG/MotionPredictor/models/" || true
          # Copy only the built rife-ncnn-vulkan executable(s) and shared libs
          mkdir -p "$PKG/rife-ncnn-vulkan/build"
          find rife-ncnn-vulkan/build -maxdepth 3 -type f \( -perm /111 -o -name '*.so' -o -name '*.dylib' -o -name '*.dll' \) -print0 \
            | xargs -0 -I{} cp -v {} "$PKG/rife-ncnn-vulkan/build/" || true
          # Copy models and docs for rife-ncnn-vulkan
          cp -rv rife-ncnn-vulkan/models "$PKG/rife-ncnn-vulkan/" || true
          cp -v rife-ncnn-vulkan/LICENSE rife-ncnn-vulkan/README.md "$PKG/rife-ncnn-vulkan/" || true
          zip -r "${PKG}.zip" "$PKG"

      - name: Prepare package layout and copy files (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $pkg = "package-${{ matrix.os }}-${{ matrix.avx2 }}"
          Remove-Item -Recurse -Force $pkg -ErrorAction SilentlyContinue
          # Copy only top-level .exe files from target\release (no deps, no .pdb, no .d files)
          Get-ChildItem -Path target\release -File | Where-Object {
            $_.Extension -eq '.exe' -and $_.Name -notlike '*.pdb' -and $_.Name -notlike '*-*' 
          } | ForEach-Object { Copy-Item -Path $_.FullName -Destination "$pkg" -Force }
          # Copy project files
          Copy-Item -Force LICENSE, README.md, log_viewer.py -Destination $pkg -ErrorAction SilentlyContinue
          New-Item -ItemType Directory -Path "$pkg\DuplicateDetect\models" -Force | Out-Null
          Copy-Item -Force -ErrorAction SilentlyContinue DuplicateDetect\models\* "$pkg\DuplicateDetect\models\"
          New-Item -ItemType Directory -Path "$pkg\MotionPredictor\models" -Force | Out-Null
          Copy-Item -Force -ErrorAction SilentlyContinue MotionPredictor\models\* "$pkg\MotionPredictor\models\"
          # Copy only rife-ncnn-vulkan executables and dlls
          New-Item -ItemType Directory -Path "$pkg\rife-ncnn-vulkan\build" | Out-Null
          $exe = "build\Release\rife-ncnn-vulkan.exe"
          Copy-Item -Verbose -Path $exe -Destination "$pkg\rife-ncnn-vulkan\build" -Force
          if (Test-Path "C:\windows\system32\vcomp140.dll") {
            Copy-Item -Verbose -Path "C:\windows\system32\vcomp140.dll" -Destination "$pkg\rife-ncnn-vulkan\build" -Force
          }
          Copy-Item -Recurse -Force -ErrorAction SilentlyContinue rife-ncnn-vulkan\models "$pkg\rife-ncnn-vulkan\"
          Copy-Item -Force -ErrorAction SilentlyContinue rife-ncnn-vulkan\LICENSE, rife-ncnn-vulkan\README.md "$pkg\rife-ncnn-vulkan\"
          Compress-Archive -Path $pkg -DestinationPath "${pkg}.zip" -Force

      - name: Upload zip as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ github.workspace }}/package-${{ matrix.os }}-${{ matrix.avx2 }}.zip
          asset_name: video_lag_fix-${{ matrix.os }}-${{ matrix.avx2 }}.zip
          asset_content_type: application/zip
